#the classifier to use
regressor : |
  ensemble.RandomForestRegressor(
    n_estimators=200,
    max_features='sqrt',
    n_jobs=-1,
    max_depth=10,
  )


telescope_type_key: telescope_type_name
telescope_events_key: telescope_events
array_events_key: array_events
runs_key: runs

multiple_telescopes: True

target_name: mc_energy

# define the number of cross validations to perform
n_cross_validations : 10

# Define the name of the category you want to find. The default is 'gamma_energy'.
# It will be written as <class_name>_prediction into the file when applying the model.
class_name: gamma_energy

# Define the name of the column that contains the name of the telescope in case you're working
# with mulitple telescopes and telescope types
telescope_type_key: telescope_type_name

training_variables:
  - num_triggered_telescopes
  - width
  - length
  - skewness
  - kurtosis
  - intensity
  - camera_id
  - telescope_type_id
  - total_intensity
  - h_max_prediction
  - distance_to_core
  - num_triggered_lst
  - num_triggered_mst
  - num_triggered_sst
