#the classifier to use
regressor : |
  ensemble.RandomForestRegressor(
    n_estimators=100,
    max_features='sqrt',
    n_jobs=-1,
    max_depth=12,
  )

n_signal: 3000

telescope_type_key: telescope_type_name
telescope_events_key: telescope_events
array_events_key: array_events
runs_key: runs

multiple_telescopes: True

target_name: mc_energy

# define the number of cross validations to perform
n_cross_validations : 5

# Define the name of the category you want to find. The default is 'gamma'.
# It will be written as <class_name>_prediction into the file when applying the model.
class_name: gamma_energy

# Define the name of the column that contains the name of the telescope in case you're working
# with mulitple telescopes and telescope types
telescope_type_key: telescope_type_name

training_variables:
  - num_triggered_telescopes
  - width
  - length
  - skewness
  - kurtosis
  - intensity
  - camera_id
  - telescope_type_id
