classifier : |
  ensemble.RandomForestClassifier(
      n_estimators=200,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=10,
      criterion='entropy',
  )


n_cross_validations : 10

telescope_type_key: telescope_type_name
telescope_events_key: telescope_events
array_events_key: array_events
runs_key: runs

multiple_telescopes: True

training_variables:
  - num_triggered_telescopes
  - width
  - length
  - skewness
  - kurtosis
  - intensity
  - camera_id
  - telescope_type_id
  - total_intensity
  - h_max_prediction
  - distance_to_core
  - num_triggered_lst
  - num_triggered_mst
  - num_triggered_sst
